# Generated by Django 2.2.5 on 2020-04-22 06:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_status', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('organisation', models.CharField(default='Learner', max_length=256)),
                ('topic1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic1', to='blog_app.Category')),
                ('topic2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic2', to='blog_app.Category')),
                ('topic3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic3', to='blog_app.Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=256)),
                ('title', models.CharField(default='Title', max_length=256)),
                ('organisation', models.CharField(default='Learner', max_length=256)),
                ('poster', models.ImageField(blank=True, upload_to='profile_pics')),
                ('author_image', models.ImageField(blank=True, upload_to='')),
                ('date_created', models.DateField(default=datetime.datetime(2020, 4, 22, 6, 2, 32, 342732, tzinfo=utc))),
                ('editor_choice', models.BooleanField(default=False)),
                ('upvote', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Category')),
                ('status', models.ForeignKey(default='draft', on_delete=django.db.models.deletion.CASCADE, to='blog_app.Status')),
            ],
        ),
    ]
