# Generated by Django 2.2.5 on 2020-04-22 10:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 10, 29, 30, 928593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters'),
        ),
    ]
