# Generated by Django 2.2.5 on 2020-04-25 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_auto_20200424_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 4, 25, 6, 54, 59, 553013, tzinfo=utc)),
        ),
    ]
