# Generated by Django 2.2.5 on 2020-04-25 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_auto_20200425_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last_4_posts',
            name='post2',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='last_4_posts',
            name='post3',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='last_4_posts',
            name='post4',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 4, 25, 7, 15, 57, 909325, tzinfo=utc)),
        ),
    ]
