# Generated by Django 2.2.5 on 2020-04-25 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_auto_20200425_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 4, 25, 8, 42, 55, 736478, tzinfo=utc)),
        ),
    ]
