# Generated by Django 2.2.5 on 2020-04-25 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_auto_20200425_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 4, 25, 9, 55, 44, 243033, tzinfo=utc)),
        ),
    ]
